--Release00001*01 -- create the database
--Build00001*01 -- create the database

USE [master]
GO

--IF (EXISTS (SELECT name 
--FROM master.dbo.sysdatabases 
--WHERE name = 'Diamond'))

--DROP DATABASE [Diamond]



go

/****** Object:  Database [Diamond]    Script Date: 22/11/2018 15:11:38 ******/
CREATE DATABASE [Diamond]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Diamond', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Diamond.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Diamond_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Diamond_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Diamond] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Diamond].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Diamond] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Diamond] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Diamond] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Diamond] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Diamond] SET ARITHABORT OFF 
GO

ALTER DATABASE [Diamond] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Diamond] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Diamond] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Diamond] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Diamond] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Diamond] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Diamond] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Diamond] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Diamond] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Diamond] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Diamond] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Diamond] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Diamond] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Diamond] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Diamond] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Diamond] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Diamond] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Diamond] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Diamond] SET RECOVERY FULL 
GO

ALTER DATABASE [Diamond] SET  MULTI_USER 
GO

ALTER DATABASE [Diamond] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Diamond] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Diamond] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Diamond] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Diamond] SET  READ_WRITE 
GO


